- lib/index.js
The PR improves the performance for the CORS middleware:
1. Remove Array.forEach() to avoid creation of closures
2. Refactor applyHeaders to a standalone function for better reuse
> Optimize applyHeaders by removing the closure

- README.md
- lib/index.js
- test/cors.js
The Express framework already implement an OPTIONS method for each exposed API which allows to discover available methods for example.
The CORS module shortcircuits this OPTIONS implementation with an HTTP 204 response.
This PR adds a `preflightContinue` options to the CORS module which allows to forward OPTIONS requests to next handlers after having added the cors headers without changing anything to the current module's default behaviour.
> Allow CORS module to forward preflights request to the next() handler

- lib/index.js
The "Vary: origin" header should be added only for specific origins, but currently the code adds it also to the wildcard origin ("*"). This would happen even if you called cors() without options, because the default origin is set to "*".
The issue is with the first condition in the configureOrigin function. If origin is not falsy, vary will be added. To fix this I just expanded the condition to check if the origin is "*".
> Fix "Vary: origin" header added for "*"

- lib/index.js
Currently it's not possible to do a OPTIONS (non-CORS) request (even with `preflightContinue` enabled from #40) to retrieve the "Allow" header of an express app.
This patch allows a config such as:
``` javascript
app.use(cors({
"credentials": true,
"origin": true,
"methods": ["GET","HEAD","PUT","PATCH","POST","DELETE", "OPTIONS"],
"exposedHeaders": ["Server", "Content-Type", "Allow", "X-Powered-By"]
}));
```
and a call with e.g. jQuery to do:
``` javascript
res.getResponseHeader('Allow')
```
> Add exposed headers to non-CORS OPTIONS request

- lib/index.js
set param to object when non object passed in to middlewareWrapper to fix issue with strict mode when a primitive value gets passed in to middlewareWrapper and causes this error:
```
/node_modules/cors/lib/index.js:188
o.origin = defaults.origin;
^
TypeError: Cannot assign to read only property 'origin' of true
```
> fix strict mode for node version past 0.10

- README.md
I struggled with this example for a few hours, and then realized that the example doesn't return an error in the callback function, which prevents the request from failing properly in the case where there's no whitelist match. I've updated it in the simplest way possible to make it work.
> Update README to fix incorrect example

- lib/index.js
Hi there!
I'm working on a little tool for debugging middleware stacks in express. Specifically for use whilst refactoring [Ghost](https://github.com/TryGhost/Ghost) but I hope other people will find it useful too.
The middleware function provided by this module is currently anonymous, which makes debugging & inspection a little bit tricky. Adding a name shouldn't have any impact other than making it easier to debug and inspect this middleware.
I have run the tests & linting, and this change (as expected) had no impact.
> Provide name for currently anonymous middleware function

- README.md
- test/cors.js
Code had incorrect header name Access-Control-Allow-Max-Age
in several places
https://www.w3.org/TR/cors/#http-access-control-max-age
Follows through on changes initially from #13
> fix docs and tests for Access-Control-Max-Age

- README.md
`optionsSuccessStatus` was missing from Configuration Options section of README.md, so I added it. 😄
> add optionsSuccessStatus to config options docs

- README.md
See expressjs/expressjs.com#719
> Follow standard style in readme

- HISTORY.md
`optionsSuccessStatus` not `optionsSucccessCode`
> docs: fix typo in history

- README.md
On the example for Configuring CORS Async, the `else` keyword has no spaces between itself and the curly braces. This improves the readibility of the statement and uses the same spacing as used in the example for Configuring CORS w/ Dynamic Origin.
> docs: improve readability on if-else statement

- README.md
A lot of times when using the code snippet for dynamic origins, developers miss out on cases where origin is not present. For example, while using a Rest tool like Postman or making requests from a server.
> Added help text for cases where origin is not present

- HISTORY.md
- lib/index.js
- test/test.js
Hey,
According to [this spec](https://www.w3.org/TR/cors/#access-control-max-age-response-header) when `Access-Control-Max-Age` is not set, it is up to the user agent to decide the value.
The check `options.maxAge` is faulty when `maxAge` equals to zero, causing it to return `null`, not 0 and different behaviors on different browsers.
Thanks!
Tom
> Fixed support for maxAge=0

- README.md
The example [here](https://github.com/expressjs/cors#configuring-cors-w-dynamic-origin) to provide a function to allow dynamic origins doesn't behave the same way as when you pass strings, arrays of strings, arrays of regexps etc as the allowed origin.
If you pass an origin function that calls back with an error, the error propagates onwards preventing the route handler that would otherwise be called from being called, and you get an unsuccessful HTTP response.
This has other undesirable side effects like preventing non-browser access to a server (#142 updated the docs to suggest a workaround for this), and preventing same-origin access to a server using the CORS middleware (which there is no workaround for, unless you count including the domains intending to do same-origin requests in …
> Suggest passing false for disallowed domains, not erroring

- README.md
Most of the organization such as Microsoft (GitHub) and UK NCSC suggest avoiding terms like "Blacklist" and "Whitelist" due to racial stereotyping. It suggests the use of "blocklist" and "allowlist" instead.
I suggest the community as an extremely popular express middle-ware we can support and involve this "Black Lives Matter" movement too.
https://www.bbc.com/news/technology-53050955
zdnet.com/article/uk-ncsc-to-stop-using-whitelist-and-blacklist-due-to-racial-stereotyping/
> Changed the term whitelist to allowlist in Documentation

- lib/index.js
Some functions are being called with "req" as second parameter, but it's not required nor is useful in any way, this does not affect the functionality but this should not be done, javascript allows it but it is a little confusing when reading it.
example:
headers.push(configureCredentials(options, **req**)); ---> headers.push(configureCredentials(options));
the function is declared this way:
`function configureCredentials(options) {...`
> Fix functions call with extra parameter

- README.md
> :bug: Fix readme status badge

- .github/workflows/ci.yml
This PR fixes [nyc](https://github.com/istanbuljs/nyc) version to 14.1.1 when running tests in node 8. `nyc 15.x` requires a `yargs` package version that requires node >=10.
I've also added the latest versions of node (17, 18, 19, 20, 21 and 22) to the matrix.
Related to https://github.com/jshttp/http-errors/issues/108
> ci: fix errors in ci github action for node 8

- test/test.js
This Pull Request addresses an issue regarding the testing of the handling and generation of `Access-Control-Allow-Headers` header. Through the application of mutation testing, I have identified a potential mutation in the configuration logic that was not covered by the existing tests (issue fully explain in this [threat](https://github.com/expressjs/cors/issues/319)).
**Proposed Change**
To mitigate this, I suggest changing the assertion method from `assert.equal` to `assert.strictEqual` in the `test/test.js` file, specifically at line 444. This alteration would ensure that the tests verify not only the value but also the exact type of the header content, thereby preventing potential type coercion issues.
**Additional Information**
This Pull Request has been created following the …
> test: improved test robustness

- README.md
The site is no longer being hosted. Better to not have a broken link in the readme.
Resolves #343 
---
labels: require-triage
---
> docs: remove broken link to demo site
